server.servlet.session.persistent=false
spring.thymeleaf.check-template-location=false
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
springdoc.api-docs.path=/api-docs
springdoc.show-actuator=true

# RAC connection pool settings
rac.pool.ttl-seconds=300
rac.pool.max-size=100
rac.pool.cleanup-interval-ms=60000
